# Generated by Django 5.0 on 2024-06-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchangemst',
            name='update_date',
            field=models.DateField(default='2024-06-21'),
            preserve_default=False,
        ),
    ]
